apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong

  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: ping-log
          persistentVolumeClaim:
            claimName: ping-log-claim
      containers:
        - name: ping-pong
          image: emanueletoma/kubernetes:ping-pong
          imagePullPolicy: Always
          volumeMounts:
            - name: ping-log
              mountPath: /data
          env:
            - name: PORT
              value: "3456"

        - name: log-output
          image: emanueletoma/kubernetes:log-output
          imagePullPolicy: Always
          volumeMounts:
            - name: ping-log
              mountPath: /data
          env:
            - name: PORT
              value: "2345"
