apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: ping-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong

  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: emanueletoma/kubernetes:ping-pong
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3456"
            - name: DATABASE_URL
              value: "postgresql://admin:password@postgres-svc:5432/pinglogdb"

        - name: log-output
          image: emanueletoma/kubernetes:log-output
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "2345"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
