apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-volume
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: emanueletoma/kubernetes:todo-app
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: FRONTEND_PORT
            - name: PUBLIC_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: BACKEND_URL

        - name: todo-backend
          image: emanueletoma/kubernetes:todo-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: todo-app-volume
              mountPath: /data
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: BACKEND_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL