apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 7000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 8000
