apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - name: frontend
      protocol: TCP
      port: 7000
      targetPort: 7000

    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000